//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string Add_Encrypted_Files_Extension {
            get {
                return ResourceManager.GetString("Add_Encrypted_Files_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a new file extension.
        /// </summary>
        internal static string Add_New_File_Extension {
            get {
                return ResourceManager.GetString("Add_New_File_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string Add_Priority_Files_Extension {
            get {
                return ResourceManager.GetString("Add_Priority_Files_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Give the name of the backup : .
        /// </summary>
        internal static string Ask_Backup_Name {
            get {
                return ResourceManager.GetString("Ask_Backup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Give the name of the backup you want to delete : .
        /// </summary>
        internal static string Ask_Backup_Name_Delete {
            get {
                return ResourceManager.GetString("Ask_Backup_Name_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Give the name of the backup you want to rename : .
        /// </summary>
        internal static string Ask_Backup_Name_Rename {
            get {
                return ResourceManager.GetString("Ask_Backup_Name_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Give the name of the save work to execute : .
        /// </summary>
        internal static string Ask_Backup_Name_ToExecute {
            get {
                return ResourceManager.GetString("Ask_Backup_Name_ToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Give the new name of the backup.
        /// </summary>
        internal static string Ask_Backup_New_Name_Rename {
            get {
                return ResourceManager.GetString("Ask_Backup_New_Name_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Give the source path directory : .
        /// </summary>
        internal static string Ask_Backup_Source_Path {
            get {
                return ResourceManager.GetString("Ask_Backup_Source_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Give the target path directory : .
        /// </summary>
        internal static string Ask_Backup_Target_Path {
            get {
                return ResourceManager.GetString("Ask_Backup_Target_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Give the type [d = differential / c =complete]: .
        /// </summary>
        internal static string Ask_Backup_Type {
            get {
                return ResourceManager.GetString("Ask_Backup_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The extension must starts with a dot.
        /// </summary>
        internal static string Ask_Informations_Add_File_Extension {
            get {
                return ResourceManager.GetString("Ask_Informations_Add_File_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, fill all the information when creating a backup.
        /// </summary>
        internal static string Ask_Informations_Create_Backup {
            get {
                return ResourceManager.GetString("Ask_Informations_Create_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which language do you want ? [fr/en] : .
        /// </summary>
        internal static string Ask_Language {
            get {
                return ResourceManager.GetString("Ask_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, enter a valid input.
        /// </summary>
        internal static string Ask_Valid_Input {
            get {
                return ResourceManager.GetString("Ask_Valid_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup created.
        /// </summary>
        internal static string Backup_Created {
            get {
                return ResourceManager.GetString("Backup_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup name.
        /// </summary>
        internal static string Backup_Name {
            get {
                return ResourceManager.GetString("Backup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backups.
        /// </summary>
        internal static string Backups {
            get {
                return ResourceManager.GetString("Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change the language.
        /// </summary>
        internal static string Change_Language {
            get {
                return ResourceManager.GetString("Change_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, enter a valid choice between 1 and 8.
        /// </summary>
        internal static string Console_Ask_Valid_Choice {
            get {
                return ResourceManager.GetString("Console_Ask_Valid_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a backup.
        /// </summary>
        internal static string Create_Backup {
            get {
                return ResourceManager.GetString("Create_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a backup.
        /// </summary>
        internal static string Delete_Backup {
            get {
                return ResourceManager.GetString("Delete_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encrypted.
        /// </summary>
        internal static string Encrypted {
            get {
                return ResourceManager.GetString("Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encrypted files.
        /// </summary>
        internal static string Encrypted_Files {
            get {
                return ResourceManager.GetString("Encrypted_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : a backup with this name already exists.
        /// </summary>
        internal static string Error_Backup_Already_Exists {
            get {
                return ResourceManager.GetString("Error_Backup_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : there is no backup with this name.
        /// </summary>
        internal static string Error_Backup_Not_Found {
            get {
                return ResourceManager.GetString("Error_Backup_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : No save work available.
        /// </summary>
        internal static string Error_NoBackup {
            get {
                return ResourceManager.GetString("Error_NoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Error : No save work of that name.
        /// </summary>
        internal static string Error_NoBackupOfThisName {
            get {
                return ResourceManager.GetString("Error_NoBackupOfThisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : you can&apos;t rename you backup with the same name.
        /// </summary>
        internal static string Error_Rename_Same_Name {
            get {
                return ResourceManager.GetString("Error_Rename_Same_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : you have already 5 backups, please delete one and retry.
        /// </summary>
        internal static string Error_Too_Many_Backups {
            get {
                return ResourceManager.GetString("Error_Too_Many_Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The following process is running, please stop it before starting a backup :.
        /// </summary>
        internal static string Error_WorkingProcess {
            get {
                return ResourceManager.GetString("Error_WorkingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : The source path you enter doesn&apos;t exist.
        /// </summary>
        internal static string Error_Wrong_SourcePath {
            get {
                return ResourceManager.GetString("Error_Wrong_SourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute all backups.
        /// </summary>
        internal static string Execute_All_Backups {
            get {
                return ResourceManager.GetString("Execute_All_Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute a save work.
        /// </summary>
        internal static string Execute_Backup {
            get {
                return ResourceManager.GetString("Execute_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit the application.
        /// </summary>
        internal static string Exit_App {
            get {
                return ResourceManager.GetString("Exit_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension (.pdf).
        /// </summary>
        internal static string File_Extension_Placeholder {
            get {
                return ResourceManager.GetString("File_Extension_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter backups by name.
        /// </summary>
        internal static string Filter_Backup {
            get {
                return ResourceManager.GetString("Filter_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Homepage.
        /// </summary>
        internal static string Home_Page {
            get {
                return ResourceManager.GetString("Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No backup found.
        /// </summary>
        internal static string Info_No_Backup {
            get {
                return ResourceManager.GetString("Info_No_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log format.
        /// </summary>
        internal static string Log_Format {
            get {
                return ResourceManager.GetString("Log_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prioritized files.
        /// </summary>
        internal static string Priority_Files {
            get {
                return ResourceManager.GetString("Priority_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove the selection.
        /// </summary>
        internal static string Remove_Encrypted_Files_Extension {
            get {
                return ResourceManager.GetString("Remove_Encrypted_Files_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove the selection.
        /// </summary>
        internal static string Remove_Priority_Files_Extension {
            get {
                return ResourceManager.GetString("Remove_Priority_Files_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename a backup.
        /// </summary>
        internal static string Rename_Backup {
            get {
                return ResourceManager.GetString("Rename_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search a backup.
        /// </summary>
        internal static string Search_Backup {
            get {
                return ResourceManager.GetString("Search_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display all backups.
        /// </summary>
        internal static string Show_Backups {
            get {
                return ResourceManager.GetString("Show_Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source path.
        /// </summary>
        internal static string Source_Path {
            get {
                return ResourceManager.GetString("Source_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à successfully executed.
        /// </summary>
        internal static string Success_Execution {
            get {
                return ResourceManager.GetString("Success_Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target path.
        /// </summary>
        internal static string Target_Path {
            get {
                return ResourceManager.GetString("Target_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type : complete.
        /// </summary>
        internal static string Type_Complete {
            get {
                return ResourceManager.GetString("Type_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type : differential.
        /// </summary>
        internal static string Type_Differential {
            get {
                return ResourceManager.GetString("Type_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open the user documentation in your web browser.
        /// </summary>
        internal static string User_Doc_Link {
            get {
                return ResourceManager.GetString("User_Doc_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello.
        /// </summary>
        internal static string Welcome_1 {
            get {
                return ResourceManager.GetString("Welcome_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to EasySave v3.0.
        /// </summary>
        internal static string Welcome_2 {
            get {
                return ResourceManager.GetString("Welcome_2", resourceCulture);
            }
        }
    }
}
