//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the name of the backup : .
        /// </summary>
        internal static string Ask_Backup_Name {
            get {
                return ResourceManager.GetString("Ask_Backup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the name of the backup you want to delete : .
        /// </summary>
        internal static string Ask_Backup_Name_Delete {
            get {
                return ResourceManager.GetString("Ask_Backup_Name_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the name of the backup you want to rename : .
        /// </summary>
        internal static string Ask_Backup_Name_Rename {
            get {
                return ResourceManager.GetString("Ask_Backup_Name_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the name of the save work to execute : .
        /// </summary>
        internal static string Ask_Backup_Name_ToExecute {
            get {
                return ResourceManager.GetString("Ask_Backup_Name_ToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the new name of the backup.
        /// </summary>
        internal static string Ask_Backup_New_Name_Rename {
            get {
                return ResourceManager.GetString("Ask_Backup_New_Name_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the source path directory : .
        /// </summary>
        internal static string Ask_Backup_Source_Path {
            get {
                return ResourceManager.GetString("Ask_Backup_Source_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the target path directory : .
        /// </summary>
        internal static string Ask_Backup_Target_Path {
            get {
                return ResourceManager.GetString("Ask_Backup_Target_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the type [d = differential / c =complete]: .
        /// </summary>
        internal static string Ask_Backup_Type {
            get {
                return ResourceManager.GetString("Ask_Backup_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which language do you want ? [fr/en] : .
        /// </summary>
        internal static string Ask_Language {
            get {
                return ResourceManager.GetString("Ask_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a valid input.
        /// </summary>
        internal static string Ask_Valid_Input {
            get {
                return ResourceManager.GetString("Ask_Valid_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup created.
        /// </summary>
        internal static string Backup_Created {
            get {
                return ResourceManager.GetString("Backup_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup name.
        /// </summary>
        internal static string Backup_Name {
            get {
                return ResourceManager.GetString("Backup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backups.
        /// </summary>
        internal static string Backups {
            get {
                return ResourceManager.GetString("Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the language.
        /// </summary>
        internal static string Change_Language {
            get {
                return ResourceManager.GetString("Change_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a valid choice between 1 and 8.
        /// </summary>
        internal static string Console_Ask_Valid_Choice {
            get {
                return ResourceManager.GetString("Console_Ask_Valid_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a backup.
        /// </summary>
        internal static string Create_Backup {
            get {
                return ResourceManager.GetString("Create_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a backup.
        /// </summary>
        internal static string Delete_Backup {
            get {
                return ResourceManager.GetString("Delete_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : a backup with this name already exists.
        /// </summary>
        internal static string Error_Backup_Already_Exists {
            get {
                return ResourceManager.GetString("Error_Backup_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : there is no backup with this name.
        /// </summary>
        internal static string Error_Backup_Not_Found {
            get {
                return ResourceManager.GetString("Error_Backup_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : No save work available.
        /// </summary>
        internal static string Error_NoBackup {
            get {
                return ResourceManager.GetString("Error_NoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : Error : No save work of that name.
        /// </summary>
        internal static string Error_NoBackupOfThisName {
            get {
                return ResourceManager.GetString("Error_NoBackupOfThisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : you can&apos;t rename you backup with the same name.
        /// </summary>
        internal static string Error_Rename_Same_Name {
            get {
                return ResourceManager.GetString("Error_Rename_Same_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : you have already 5 backups, please delete one and retry.
        /// </summary>
        internal static string Error_Too_Many_Backups {
            get {
                return ResourceManager.GetString("Error_Too_Many_Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following process is running, please stop it before starting a backup :.
        /// </summary>
        internal static string Error_WorkingProcess {
            get {
                return ResourceManager.GetString("Error_WorkingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : The source path you enter doesn&apos;t exist.
        /// </summary>
        internal static string Error_Wrong_SourcePath {
            get {
                return ResourceManager.GetString("Error_Wrong_SourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute all backups.
        /// </summary>
        internal static string Execute_All_Backups {
            get {
                return ResourceManager.GetString("Execute_All_Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute a save work.
        /// </summary>
        internal static string Execute_Backup {
            get {
                return ResourceManager.GetString("Execute_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        internal static string Exit_App {
            get {
                return ResourceManager.GetString("Exit_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        internal static string Home_Page {
            get {
                return ResourceManager.GetString("Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup found.
        /// </summary>
        internal static string Info_No_Backup {
            get {
                return ResourceManager.GetString("Info_No_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log format.
        /// </summary>
        internal static string Log_Format {
            get {
                return ResourceManager.GetString("Log_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename a backup.
        /// </summary>
        internal static string Rename_Backup {
            get {
                return ResourceManager.GetString("Rename_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a backup.
        /// </summary>
        internal static string Search_Backup {
            get {
                return ResourceManager.GetString("Search_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display all backups.
        /// </summary>
        internal static string Show_Backups {
            get {
                return ResourceManager.GetString("Show_Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source path.
        /// </summary>
        internal static string Source_Path {
            get {
                return ResourceManager.GetString("Source_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target path.
        /// </summary>
        internal static string Target_Path {
            get {
                return ResourceManager.GetString("Target_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type : complete.
        /// </summary>
        internal static string Type_Complete {
            get {
                return ResourceManager.GetString("Type_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type : differential.
        /// </summary>
        internal static string Type_Differential {
            get {
                return ResourceManager.GetString("Type_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Welcome_1 {
            get {
                return ResourceManager.GetString("Welcome_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to EasySave v3.0.
        /// </summary>
        internal static string Welcome_2 {
            get {
                return ResourceManager.GetString("Welcome_2", resourceCulture);
            }
        }
    }
}
